# Dracula
$bg0 = rgb(282a36)
$bg1 = rgb(44475a)
$bg2 = rgb(6272a4)
$fg = rgb(f8f8f2)
$red = rgb(ff5555)
$orange = rgb(ffb86c)
$yellow = rgb(f1fa8c)
$green = rgb(50fa7b)
$cyan = rgb(8be9fd)
$blue = rgb(bd93f9)
$purple = rgb(bd93f9)
$pink = rgb(ff79c6)
$active_border = rgba(bd93f9ee)
$inactive_border = rgba(44475aaa)
$active_border = rgba(bd93f9ee)
$inactive_border = rgba(44475aaa)
