# Everforest Dark
$bg0 = rgb(2d353b)
$bg1 = rgb(3d484d)
$bg2 = rgb(475258)
$bg3 = rgb(4f5b58)
$fg = rgb(d3c6aa)
$red = rgb(e67e80)
$orange = rgb(e69875)
$yellow = rgb(dbbc7f)
$green = rgb(a7c080)
$cyan = rgb(83c092)
$blue = rgb(7fbbb3)
$purple = rgb(d699b6)
$active_border = rgba(a7c080ee)
$inactive_border = rgba(475258aa)
$active_border = rgba(a7c080ee)
$inactive_border = rgba(475258aa)
