# Gruvbox Dark
$bg0 = rgb(282828)
$bg1 = rgb(3c3836)
$bg2 = rgb(504945)
$bg3 = rgb(665c54)
$bg4 = rgb(7c6f64)
$fg = rgb(ebdbb2)
$red = rgb(cc241d)
$orange = rgb(d65d0e)
$yellow = rgb(d79921)
$green = rgb(98971a)
$cyan = rgb(689d6a)
$blue = rgb(458588)
$purple = rgb(b16286)
$pink = rgb(fe8019)
$active_border = rgba(d65d0eee)
$inactive_border = rgba(504945aa)
$active_border = rgba(d65d0eee)
$inactive_border = rgba(504945aa)
