# Kanagawa
$bg0 = rgb(1f1f28)
$bg1 = rgb(2a2a37)
$bg2 = rgb(223249)
$bg3 = rgb(363646)
$fg = rgb(dcd7ba)
$red = rgb(c34043)
$orange = rgb(ffa066)
$yellow = rgb(c0a36e)
$green = rgb(76946a)
$cyan = rgb(6a9589)
$blue = rgb(7e9cd8)
$purple = rgb(957fb8)
$active_border = rgba(7e9cd8ee)
$inactive_border = rgba(363646aa)

$active_border = rgba(7e9cd8ee)
$inactive_border = rgba(363646aa)
