# Material Deep Ocean
$bg0 = rgb(0f111a)
$bg1 = rgb(1a1c25)
$bg2 = rgb(1f2233)
$bg3 = rgb(292d3e)
$fg = rgb(8f93a2)
$red = rgb(f07178)
$orange = rgb(f78c6c)
$yellow = rgb(ffcb6b)
$green = rgb(c3e88d)
$cyan = rgb(89ddff)
$blue = rgb(82aaff)
$purple = rgb(c792ea)
$active_border = rgba(82aaffee)
$inactive_border = rgba(1f2233aa)
