# Nightfox
$bg0 = rgb(192330)
$bg1 = rgb(212e3f)
$bg2 = rgb(2b3b51)
$bg3 = rgb(3b4b67)
$fg = rgb(cdcecf)
$red = rgb(c94f6d)
$orange = rgb(f4a261)
$yellow = rgb(dbc074)
$green = rgb(81b29a)
$cyan = rgb(63cdcf)
$blue = rgb(719cd6)
$purple = rgb(9d79d6)
$active_border = rgba(719cd6ee)
$inactive_border = rgba(2b3b51aa)
$active_border = rgba(719cd6ee)
$inactive_border = rgba(2b3b51aa)
