# Nord
$polar1 = rgb(2e3440)
$polar2 = rgb(3b4252)
$polar3 = rgb(434c5e)
$polar4 = rgb(4c566a)
$snow1 = rgb(d8dee9)
$snow2 = rgb(e5e9f0)
$snow3 = rgb(eceff4)
$frost1 = rgb(8fbcbb)
$frost2 = rgb(88c0d0)
$frost3 = rgb(81a1c1)
$frost4 = rgb(5e81ac)
$red = rgb(bf616a)
$orange = rgb(d08770)
$yellow = rgb(ebcb8b)
$green = rgb(a3be8c)
$purple = rgb(b48ead)
$active_border = rgba(81a1c1ee)
$inactive_border = rgba(3b4252aa)
$active_border = rgba(81a1c1ee)
$inactive_border = rgba(3b4252aa)
