# One Dark
$bg0 = rgb(282c34)
$bg1 = rgb(353b45)
$bg2 = rgb(3e4451)
$bg3 = rgb(545862)
$fg = rgb(abb2bf)
$red = rgb(e06c75)
$orange = rgb(d19a66)
$yellow = rgb(e5c07b)
$green = rgb(98c379)
$cyan = rgb(56b6c2)
$blue = rgb(61afef)
$purple = rgb(c678dd)
$active_border = rgba(61afefee)
$inactive_border = rgba(3e4451aa)
$active_border = rgba(61afefee)
$inactive_border = rgba(3e4451aa)
