# Oxocarbon
$bg0 = rgb(161616)
$bg1 = rgb(262626)
$bg2 = rgb(393939)
$bg3 = rgb(525252)
$fg = rgb(f2f4f8)
$red = rgb(ff7eb6)
$orange = rgb(3ddbd9)
$yellow = rgb(ffe97b)
$green = rgb(42be65)
$cyan = rgb(08bdba)
$blue = rgb(78a9ff)
$purple = rgb(be95ff)
$active_border = rgba(78a9ffee)
$inactive_border = rgba(393939aa)
$active_border = rgba(78a9ffee)
$inactive_border = rgba(393939aa)
