# Solarized Dark
$bg0 = rgb(002b36)
$bg1 = rgb(073642)
$bg2 = rgb(586e75)
$bg3 = rgb(657b83)
$fg = rgb(839496)
$red = rgb(dc322f)
$orange = rgb(cb4b16)
$yellow = rgb(b58900)
$green = rgb(859900)
$cyan = rgb(2aa198)
$blue = rgb(268bd2)
$purple = rgb(d33682)
$active_border = rgba(268bd2ee)
$inactive_border = rgba(073642aa)
