# Spaceduck
$bg0 = rgb(0f111b)
$bg1 = rgb(1b1c36)
$bg2 = rgb(30365f)
$bg3 = rgb(686f9a)
$fg = rgb(ecf0c1)
$red = rgb(e33400)
$orange = rgb(e39400)
$yellow = rgb(f2ce00)
$green = rgb(5ccc96)
$cyan = rgb(00a3cc)
$blue = rgb(00a3cc)
$purple = rgb(7a5ccc)
$active_border = rgba(7a5cccee)
$inactive_border = rgba(30365faa)
$active_border = rgba(7a5cccee)
$inactive_border = rgba(30365faa)
