# Tokyo Night
$bg0 = rgb(1a1b26)
$bg1 = rgb(1e2030)
$bg2 = rgb(24283b)
$bg3 = rgb(313244)
$bg4 = rgb(414868)
$fg = rgb(c0caf5)
$red = rgb(f7768e)
$orange = rgb(ff9e64)
$yellow = rgb(e0af68)
$green = rgb(9ece6a)
$cyan = rgb(7dcfff)
$blue = rgb(7aa2f7)
$purple = rgb(bb9af7)
$pink = rgb(f7768e)
$active_border = rgba(7aa2f7ee)
$inactive_border = rgba(414868aa)
$active_border = rgba(7aa2f7ee)
$inactive_border = rgba(414868aa)
