# ---------- Font ----------
font_family      monospace
#font_size        20.0

# ---------- Keybinds ----------
map --allow-fallback=shifted,ascii ctrl+c copy_or_noop
map --allow-fallback=shifted,ascii ctrl+v paste_from_clipboard
map ctrl+shift+ä new_tab
map ctrl+pgup previous_tab
map ctrl+pgdn next_tab
map ctrl+shift+pgup move_tab_backward
map ctrl+shift+pgdn move_tab_forward
enabled_layouts splits
map ctrl+shift+down launch --location=hsplit
map ctrl+shift+right launch --location=vsplit
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down


# ---------- Scrollback ----------
scrollback_lines 5000

# ---------- Style ----------
  background #0f111b
#  foreground #ecf0c1
  foreground #ffffff
  cursor #ecf0c1
#  selection_background #686f9a
#  color0 #000000
#  color8 #686f9a
#  color1 #e33400
#  color9 #e33400
#  color2 #5ccc96
#  color10 #5ccc96
#  color3 #b3a1e6
#  color11 #b3a1e6
#  color4 #00a3cc
#  color12 #00a3cc
#  color5 #f2ce00
#  color13 #f2ce00
#  color6 #7a5ccc
#  color14 #7a5ccc
#  color7 #686f9a
## color15 #f0f1ce
#  color15 #ffffff
#  selection_foreground #ffffff

hide_window_decorations yes
# ---------- Cursor ----------
cursor_shape     beam
cursor_blink_interval 0
