#exec-once = dms run 
exec-once = qs -c noctalia-shell
#exec-once = ~/.config/rofi/restore_wallpaper.sh
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprpolkitagent
exec-once = hypridle
exec-once = sleep 5 && openrgb --profile flame --startminimized
exec-once = hyprctl setcursor macOS 24
#exec-once=/usr/bin/dunst

