decoration {
    rounding = 0
    rounding_power = 0
    active_opacity = 0.9
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 9
        passes = 2
        new_optimizations = true
        vibrancy = 0.1696
        popups = true
    }
}
