general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = $active_border
    col.inactive_border = $inactive_border
#    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
#    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

xwayland {
    force_zero_scaling = true
}
