###################
# GLOBAL FIXES
###################

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

###################
# APP BEHAVIOR
###################

# hyprland-run
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = on
}

# satty
windowrule = float on, match:class com.gabm.satty
windowrule = center on, match:class com.gabm.satty

# GTK file picker
windowrule = float on, match:class xdg-desktop-portal-gtk
windowrule = center on, match:class xdg-desktop-portal-gtk

# Open/Save dialogs
windowrule = float on, match:title ^(Open File|Save As|Export|Import)$
windowrule = center on, match:title ^(Open File|Save As|Export|Import)$

###################
# DOLPHIN
###################

windowrule = float on, match:class ^(org.kde.dolphin)$
windowrule = center on, match:class ^(org.kde.dolphin)$
windowrule = size 1200 800, match:class ^(org.kde.dolphin)$
windowrule = opacity 0.85 override 0.85 override, match:class ^(org.kde.dolphin)$

###################
# KEEPASSXC
###################

windowrule = float on, match:class ^(org.keepassxc.KeePassXC)$
windowrule = center on, match:class ^(org.keepassxc.KeePassXC)$
windowrule = size 1000 700, match:class ^(org.keepassxc.KeePassXC)$

###################
# MEDIA / BROWSERS
###################

windowrule = no_blur on, match:class Dunst
windowrule = opacity 1.0 override, match:class Dunst

windowrule = no_blur on, match:class (firefox|com.stremio.stremio)
windowrule = opaque on, match:class (firefox|com.stremio.stremio)

###################
# SPOTIFY
###################
#windowrule = opacity 0.5, match:class ^(Spotify)$
#windowrule = float on, match:class ^(Spotify)$
#windowrule = center on, match:class ^(Spotify)$

windowrule {
    name = spotify-config
    match:class = ^(Spotify)$
    float = on
    opacity = 0.85 0.85
    center = on
}
