$image = Null

$background = rgba(000000ff)

$error = rgba(dd0000ff)

$error_container = rgba(8c1d18ff)

$inverse_on_surface = rgba(e6f0ffff)

$inverse_primary = rgba(ffffffff)

$inverse_surface = rgba(000000ff)

$on_background = rgba(ffffffff)

$on_error = rgba(601410ff)

$on_error_container = rgba(f9dedcff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(e6f0ffff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(000000ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(e6f0ffff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(000000ff)

$on_surface = rgba(e6f0ffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(e6f0ffff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(000000ff)

$outline = rgba(555555ff)

$outline_variant = rgba(000000ff)

$primary = rgba(ffffffff)

$primary_container = rgba(cc5200ff)

$primary_fixed = rgba(cc5200ff)

$primary_fixed_dim = rgba(ffffffff)

$scrim = rgba(000000ff)

$secondary = rgba(999999ff)

$secondary_container = rgba(000000ff)

$secondary_fixed = rgba(999999ff)

$secondary_fixed_dim = rgba(999999ff)

$shadow = rgba(000000ff)

$source_color = rgba(ffffffff)

$surface = rgba(000000ff)

$surface_bright = rgba(000000ff)

$surface_container = rgba(000000ff)

$surface_container_high = rgba(000000ff)

$surface_container_highest = rgba(000000ff)

$surface_container_low = rgba(000000ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(000000ff)

$surface_tint = rgba(ff6600ff)

$surface_variant = rgba(000000ff)

$tertiary = rgba(999999ff)

$tertiary_container = rgba(000000ff)

$tertiary_fixed = rgba(999999ff)

$tertiary_fixed_dim = rgba(999999ff)

